apiVersion: v1
kind: Service
metadata:
  name: lamp-apache
  labels:
    app: lamp-apache
spec:
  ports:
    - port: 80
  selector:
    app: lamp-apache
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lamp-apache-pv-claim
  labels:
    app: lamp-apache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-apache
  labels:
    app: lamp-apache
spec:
  selector:
    matchLabels:
      app: lamp-apache
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: lamp-apache
        tier: frontend
    spec:
      containers:
      - image: php:8.2-apache
        name: lamp-apache
        env:
        - name: PMA_HOST
          value: lamp-mysql
        - name: PMA_PORT
          value: "3306"
        - name: LAMP_DB_HOST
          value: lamp-mysql
        - name: LAMP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        - name: LAMP_DB_USER
          value: testuser
        ports:
        - containerPort: 80
          name: lamp-apache
        volumeMounts:
        - name: lamp-apache-persistent-storage
          mountPath: /var/www/html 
      volumes:
      - name: lamp-apache-persistent-storage
        hostPath: 
          path: /data/src/kubernetes/deploy/yaml/apache_phpadmin_mysql/APACHE_MYSQL/html
